### ISSUE TITLE
Warn users that the site is not mobile-friendly

### ISSUE THREAD

**Issue by gauravkeerthi** [bettersg/tobeyou_facilitator#113]
Can we put a notice on the front page to tell users that the site is optimised for desktops or tablets and is not mobile friendly?

**Comment by halfwhole** [comment]
Where would be a good place to put the notice, would something like this work?

<img width="511" alt="Screenshot 2022-06-21 at 3 02 05 PM" src="https://user-images.githubusercontent.com/41856541/174736847-90160d18-7c35-4082-91b5-f4c8722337ab.png">
